defaults: &defaults
  username: root
  password: josh123
  host: 
  adapter: mysql2
  encoding: utf8

development:
  database: kimaya_development
  <<: *defaults

test:
  database: kimaya_test
  <<: *defaults

production:
  database: kimaya_production
  <<: *defaults
